/// Generated by AssetsRefGenerator on 2021/08/12
class Res {
  static const String die = "assets/die.mp3";
  static const String logo = "assets/logo.png";
  static const String melon_cut = "assets/melon_cut_1.png";
  static const String melon_cut_right = "assets/melon_cut_right_1.png";
  static const String melon_splash = "assets/melon_splash.png";
  static const String melon_uncut = "assets/melon_uncut_1.png";
}
